# Generated by Django 5.2.4 on 2025-07-22 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("notes", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("map_link", models.URLField(blank=True)),
                ("specialties", models.TextField(blank=True)),
                (
                    "price_range",
                    models.CharField(
                        blank=True,
                        choices=[("€", "€"), ("€€", "€€"), ("€€€", "€€€")],
                        max_length=3,
                    ),
                ),
                (
                    "cana_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in euros",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "crowd_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("medium", "Medium"),
                            ("crowded", "Crowded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_visited", models.DateField(blank=True, null=True)),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Comma-separated tags"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_visited", "name"],
            },
        ),
        migrations.CreateModel(
            name="BarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bars/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="bars.bar",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
