# Generated by Django 5.2.4 on 2025-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bars", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barphoto",
            options={"ordering": ["-is_featured", "-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="barphoto",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Display this photo on the home page list for this bar",
            ),
        ),
    ]
